### ISSUE TITLE
UAT: Enhance Case summary APIs to include courtID - to help manage Application numbering

### ISSUE THREAD

**Issue by atulgupta2024** [pucardotorg/dristi#2223]
Application needs to have a CMP number. The CMP number generation requires courtID. Currently Application doesn't has access court ID. To get this, it has to call the Case API. Instead of trying to get the entire case, we will enhance the case summary APIs to include court ID 

APIS to extend 
/case/v1/search/_list
/case/v1/search/_summary

Both these APIs return a CaseSummary entity. Enhance the entity with the following fields
1. courtId - during draft stage, this could null. return the value as is i.e. null is a valid value
2. registrationDate - the case registration date. could be null, if the case has not yet been registered. Will be required for the landing page feature later 
3. registrationNumber - the case cmpNumber. could be null, if the case has not yet been registered. Will be required for the landing page feature later 

@suresh12 @subhashini-egov @Taherabharmal FYI as well

**Comment by prasanna2400** [comment]
@rajeshcherukumalli  please test

**Comment by kashish384** [comment]
Related issue:
#2283 
#2282

**Comment by rajeshcherukumalli** [comment]
Issues are resolved moving the ticket to UAT

**Comment by kashish384** [comment]
Hi@Ramu-kandimalla, PR not merged for this ticket related changes, so i am not able to update this ticket.

**Comment by Ramu-kandimalla** [comment]
HI @kashish384 @rajeshcherukumalli  Please verify in DPG Dev env

**Comment by Ramu-kandimalla** [comment]
Moving to sprint 13 release

**Comment by kashish384** [comment]
This is not fixed...yet
* the case registration date. could be null, if the case has not yet been registered
https://jam.dev/c/fa8bd66d-5ec1-438a-a3dc-325c473330b2

**Comment by kashish384** [comment]
Its wrking fine in DPG dev env.
- url: https://dristi-dev.pucar.org/digit-ui/employee/home/home-pending-task
https://dristi-dev.pucar.org/digit-ui/citizen/home/home-pending-task
- Test cases:
https://beehyv0-my.sharepoint.com/:x:/r/personal/kashish_kalirawana_beehyv_com/_layouts/15/Doc.aspx?sourcedoc=%7B090AA02F-DB24-4C80-A32E-0C2A47AE5E5B%7D&file=Book%2018.xlsx&action=editnew&mobileredirect=true&wdPreviousSession=4ce23f58-e4ab-4f9d-25af-5e28f170371d&wdNewAndOpenCt=1731413194857&wdo=4&wdOrigin=wacFileNew&wdPreviousCorrelation=2b9b3c9b-90b5-42d4-9c01-d0f2796be446&wdnd=1

**Comment by anshumanth-egov** [comment]
Cannot verify but signing off based on comment that its tested and working
